import { Job } from "./job";

export const mockJobs: Job[] = [
  {
    id: "1",
    title: "Senior Frontend Engineer",
    company: "TechFlow Solutions",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=TF",
    location: "TP. Hồ Chí Minh",
    type: "Full-time",
    level: "Senior",
    salary: "$2,000 - $3,500",
    postedAt: "2026-01-29T10:00:00.000Z",
    description: "Chúng tôi đang tìm kiếm Senior Frontend Engineer để dẫn dắt team phát triển sản phẩm cốt lõi sử dụng React và Next.js.",
    skills: ["React", "TypeScript", "Next.js", "Tailwind CSS"],
    fullDescription: `Chúng tôi đang tìm kiếm một Senior Frontend Engineer tài năng để gia nhập đội ngũ phát triển sản phẩm của TechFlow Solutions. Bạn sẽ làm việc trực tiếp với team sản phẩm để xây dựng các tính năng mới, cải thiện hiệu suất và trải nghiệm người dùng cho nền tảng SaaS phục vụ hàng nghìn khách hàng doanh nghiệp.`,
    requirements: ["Tối thiểu 5 năm kinh nghiệm phát triển Frontend", "Thành thạo React, TypeScript và Next.js", "Có kinh nghiệm với CSS-in-JS hoặc Tailwind CSS", "Tiếng Anh giao tiếp tốt"],
    responsibilities: ["Thiết kế và phát triển các tính năng frontend mới", "Tối ưu hóa hiệu suất và trải nghiệm người dùng", "Code review và đảm bảo chất lượng code", "Mentor junior developers trong team"],
    benefits: ["Mức lương cạnh tranh + thưởng hấp dẫn", "ESOP (Cổ phần công ty)", "Bảo hiểm sức khỏe cao cấp", "Laptop MacBook Pro mới nhất", "Team building hàng quý"],
    deadline: "2026-03-01T23:59:59.000Z",
    workingHours: "9:00 - 18:00, Thứ 2 - Thứ 6",
    teamSize: "10-15 người",
    reportTo: "Engineering Manager",
    companyInfo: {
      name: "TechFlow Solutions",
      logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=TF",
      coverImageUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=400&fit=crop",
      description: "TechFlow Solutions là startup công nghệ hàng đầu Việt Nam, chuyên cung cấp giải pháp SaaS cho doanh nghiệp.",
      website: "https://techflow.vn",
      industry: "SaaS / Enterprise Software",
      size: "50-100 nhân viên",
      founded: 2020,
    },
    locationInfo: {
      city: "TP. Hồ Chí Minh",
      district: "Quận 1",
      address: "Tầng 15, Bitexco Financial Tower, 2 Hải Triều, Bến Nghé",
      coordinates: { lat: 10.7719, lng: 106.7048 },
    },
    contactInfo: {
      name: "Nguyễn Thị Mai Anh",
      title: "HR Manager",
      email: "maianh.nguyen@techflow.vn",
      phone: "+84 909 123 456",
    },
  },
  {
    id: "2",
    title: "Product Designer (UI/UX)",
    company: "Creative Pulse",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=CP",
    location: "Remote",
    type: "Remote",
    level: "Middle",
    salary: "$1,500 - $2,500",
    postedAt: "2026-01-31T10:00:00.000Z",
    description: "Tham gia team thiết kế để tạo ra trải nghiệm người dùng tuyệt vời cho các khách hàng toàn cầu.",
    skills: ["Figma", "UI/UX", "Prototyping", "Design Systems"],
    fullDescription: `Creative Pulse đang mở rộng team Design và tìm kiếm Product Designer có đam mê với UI/UX. Bạn sẽ làm việc trực tiếp với các khách hàng quốc tế, thiết kế giao diện cho các ứng dụng web và mobile đa dạng.`,
    requirements: ["3+ năm kinh nghiệm thiết kế UI/UX", "Thành thạo Figma", "Portfolio ấn tượng", "Tiếng Anh giao tiếp tốt"],
    benefits: ["Làm việc 100% remote", "Lịch làm việc linh hoạt", "Bảo hiểm sức khỏe", "Ngân sách cho thiết bị"],
    workingHours: "Linh hoạt (Remote)",
    teamSize: "5-8 người",
    companyInfo: {
      name: "Creative Pulse",
      logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=CP",
      coverImageUrl: "https://images.unsplash.com/photo-1542744094-3a31f272c490?w=800&h=400&fit=crop",
      description: "Creative Pulse là agency thiết kế chuyên phục vụ khách hàng startup và doanh nghiệp toàn cầu.",
      website: "https://creativepulse.io",
      industry: "Design Agency",
      size: "20-50 nhân viên",
      founded: 2018,
    },
    locationInfo: { city: "Remote", address: "Làm việc từ xa - Toàn cầu" },
    contactInfo: {
      name: "Trần Văn Hùng",
      title: "Design Lead",
      email: "hung.tran@creativepulse.io",
      phone: "+84 912 345 678",
    },
  },
  {
    id: "3",
    title: "Backend Developer (Go)",
    company: "NextGen Fintech",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=NG",
    location: "Hà Nội",
    type: "Full-time",
    level: "Junior",
    salary: "$800 - $1,500",
    postedAt: "2026-01-30T10:00:00.000Z",
    description: "Cơ hội tuyệt vời cho Junior Developer học hỏi và làm việc với hệ thống Microservices hiệu năng cao.",
    skills: ["Go", "PostgreSQL", "Docker", "gRPC"],
    fullDescription: `NextGen Fintech đang tìm kiếm Junior Backend Developer có đam mê với Go và muốn phát triển trong lĩnh vực fintech.`,
    requirements: ["0-2 năm kinh nghiệm lập trình", "Có kiến thức cơ bản về Go", "Hiểu biết về databases", "Ham học hỏi"],
    benefits: ["Mentorship từ senior engineers", "Lộ trình phát triển rõ ràng", "Bảo hiểm đầy đủ"],
    workingHours: "9:00 - 18:00, Thứ 2 - Thứ 6",
    teamSize: "8-12 người",
    companyInfo: {
      name: "NextGen Fintech",
      logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=NG",
      coverImageUrl: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=800&h=400&fit=crop",
      description: "NextGen Fintech xây dựng các giải pháp thanh toán và banking cho thế hệ tiếp theo.",
      website: "https://nextgenfintech.vn",
      industry: "Fintech / Banking",
      size: "100-200 nhân viên",
      founded: 2019,
    },
    locationInfo: {
      city: "Hà Nội",
      district: "Cầu Giấy",
      address: "Tầng 12, Tòa nhà Keangnam Landmark, Phạm Hùng",
      coordinates: { lat: 21.0168, lng: 105.7837 },
    },
    contactInfo: {
      name: "Lê Hoàng Nam",
      title: "Tech Recruiter",
      email: "nam.le@nextgenfintech.vn",
      phone: "+84 903 456 789",
    },
  },
  {
    id: "4",
    title: "Fullstack Engineer",
    company: "Global Tech",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=GT",
    location: "Đà Nẵng",
    type: "Contract",
    level: "Senior",
    salary: "$2,500 - $4,000",
    postedAt: "2026-01-26T10:00:00.000Z",
    description: "Xây dựng các hệ thống phức tạp sử dụng Node.js và React. Yêu cầu kinh nghiệm 5+ năm.",
    skills: ["Node.js", "React", "MongoDB", "AWS"],
    requirements: ["5+ năm kinh nghiệm Fullstack", "Thành thạo Node.js và React", "Có kinh nghiệm với cloud"],
    benefits: ["Rate cạnh tranh", "Làm việc với khách hàng quốc tế", "Cơ hội chuyển full-time"],
    workingHours: "Flexible (overlap với US timezone)",
    teamSize: "5-7 người",
    companyInfo: {
      name: "Global Tech",
      logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=GT",
      coverImageUrl: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&h=400&fit=crop",
      description: "Global Tech là công ty outsourcing hàng đầu với văn phòng tại Đà Nẵng.",
      website: "https://globaltech.com.vn",
      industry: "IT Outsourcing",
      size: "200-500 nhân viên",
      founded: 2015,
    },
    locationInfo: {
      city: "Đà Nẵng",
      district: "Hải Châu",
      address: "Tầng 8, Indochina Riverside Tower, 74 Bạch Đằng",
      coordinates: { lat: 16.0726, lng: 108.2264 },
    },
    contactInfo: {
      name: "Phạm Thị Lan",
      title: "HR Business Partner",
      email: "lan.pham@globaltech.com.vn",
      phone: "+84 905 678 901",
    },
  },
  {
    id: "5",
    title: "React Native Developer",
    company: "AppMasters",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=AM",
    location: "TP. Hồ Chí Minh",
    type: "Full-time",
    level: "Middle",
    salary: "$1,200 - $2,200",
    postedAt: "2026-01-31T14:30:00.000Z",
    description: "Phát triển ứng dụng mobile tiên tiến cho hàng triệu người dùng trên iOS và Android.",
    skills: ["React Native", "TypeScript", "iOS", "Android"],
    requirements: ["2-4 năm kinh nghiệm React Native", "Có kinh nghiệm publish app", "Hiểu biết về native modules"],
    benefits: ["Lương cạnh tranh", "Bảo hiểm sức khỏe", "Team trẻ năng động"],
    workingHours: "9:00 - 18:00, Thứ 2 - Thứ 6",
    teamSize: "6-10 người",
    companyInfo: {
      name: "AppMasters",
      logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=AM",
      coverImageUrl: "https://images.unsplash.com/photo-1551434678-e076c223a692?w=800&h=400&fit=crop",
      description: "AppMasters chuyên phát triển ứng dụng mobile với hơn 50 ứng dụng đã publish.",
      website: "https://appmasters.vn",
      industry: "Mobile Development",
      size: "30-50 nhân viên",
      founded: 2017,
    },
    locationInfo: {
      city: "TP. Hồ Chí Minh",
      district: "Quận 3",
      address: "Tầng 5, Saigon Pearl, 92 Nguyễn Hữu Cảnh",
      coordinates: { lat: 10.7867, lng: 106.7095 },
    },
    contactInfo: {
      name: "Võ Minh Tuấn",
      title: "Talent Acquisition",
      email: "tuan.vo@appmasters.vn",
      phone: "+84 908 234 567",
    },
  },
  {
    id: "6",
    title: "AI Research Intern",
    company: "SmartAI Lab",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=SA",
    location: "Remote",
    type: "Internship",
    level: "Intern",
    salary: "$300 - $600",
    postedAt: "2026-01-30T15:00:00.000Z",
    description: "Nghiên cứu và triển khai các mô hình NLP mới nhất. Được hướng dẫn bởi các chuyên gia.",
    skills: ["Python", "PyTorch", "NLP", "Machine Learning"],
    requirements: ["Sinh viên năm cuối hoặc mới tốt nghiệp", "Có kiến thức về ML/DL", "Đam mê nghiên cứu AI"],
    benefits: ["Mentorship từ các chuyên gia", "Cơ hội publish paper", "Chuyển full-time sau intern"],
    companyInfo: {
      name: "SmartAI Lab",
      logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=SA",
      coverImageUrl: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=400&fit=crop",
      description: "SmartAI Lab là phòng nghiên cứu AI hàng đầu Việt Nam.",
      website: "https://smartailab.ai",
      industry: "AI Research",
      size: "10-20 nhân viên",
      founded: 2021,
    },
    locationInfo: { city: "Remote", address: "Làm việc từ xa" },
    contactInfo: {
      name: "TS. Nguyễn Văn Khoa",
      title: "Research Director",
      email: "khoa.nguyen@smartailab.ai",
      phone: "+84 901 234 567",
    },
  },
  {
    id: "7",
    title: "DevOps Engineer",
    company: "CloudScale",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=CS",
    location: "Remote",
    type: "Remote",
    level: "Senior",
    salary: "$3,000 - $5,000",
    postedAt: "2026-01-28T10:00:00.000Z",
    description: "Mở rộng hạ tầng sử dụng Kubernetes và Terraform. Tối ưu hóa quy trình CI/CD.",
    skills: ["Kubernetes", "AWS", "Terraform", "CI/CD"],
    requirements: ["5+ năm kinh nghiệm DevOps", "Thành thạo Kubernetes", "Có chứng chỉ AWS"],
    benefits: ["Làm việc remote toàn thời gian", "Lương USD", "Bảo hiểm quốc tế"],
    companyInfo: {
      name: "CloudScale",
      logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=CS",
      coverImageUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&h=400&fit=crop",
      description: "CloudScale cung cấp dịch vụ cloud infrastructure cho doanh nghiệp lớn.",
      website: "https://cloudscale.asia",
      industry: "Cloud Services",
      size: "50-100 nhân viên",
      founded: 2018,
    },
    locationInfo: { city: "Remote", address: "Làm việc từ xa - Việt Nam" },
    contactInfo: {
      name: "Đặng Quốc Việt",
      title: "CTO",
      email: "viet.dang@cloudscale.asia",
      phone: "+84 906 789 012",
    },
  },
  {
    id: "8",
    title: "Marketing Lead",
    company: "GrowthHackerz",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=GH",
    location: "TP. Hồ Chí Minh",
    type: "Full-time",
    level: "Lead",
    salary: "$2,500 - $4,500",
    postedAt: "2026-01-24T10:00:00.000Z",
    description: "Dẫn dắt các chiến dịch marketing và thúc đẩy tăng trưởng cho sản phẩm SaaS.",
    skills: ["Digital Marketing", "SEO", "Content Strategy", "Analytics"],
    requirements: ["5+ năm kinh nghiệm Marketing", "Có kinh nghiệm lead team", "Thành thạo các công cụ analytics"],
    benefits: ["Lương cạnh tranh", "Thưởng theo KPI", "Cơ hội thăng tiến nhanh"],
    companyInfo: {
      name: "GrowthHackerz",
      logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=GH",
      coverImageUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=400&fit=crop",
      description: "GrowthHackerz là agency marketing chuyên giúp startup tăng trưởng nhanh.",
      website: "https://growthhackerz.vn",
      industry: "Digital Marketing",
      size: "20-30 nhân viên",
      founded: 2019,
    },
    locationInfo: {
      city: "TP. Hồ Chí Minh",
      district: "Quận 7",
      address: "Tầng 10, Crescent Plaza, Phú Mỹ Hưng",
      coordinates: { lat: 10.7295, lng: 106.7186 },
    },
    contactInfo: {
      name: "Hoàng Thị Thanh",
      title: "HR Director",
      email: "thanh.hoang@growthhackerz.vn",
      phone: "+84 907 890 123",
    },
  },
  {
    id: "9",
    title: "Data Engineer",
    company: "DataVerse",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=DV",
    location: "Hà Nội",
    type: "Full-time",
    level: "Middle",
    salary: "$1,500 - $2,800",
    postedAt: "2026-01-31T07:00:00.000Z",
    description: "Xây dựng và vận hành data pipelines quy mô lớn phục vụ analytics và ML.",
    skills: ["Python", "Spark", "Airflow", "BigQuery", "Kafka"],
    requirements: ["3+ năm kinh nghiệm Data Engineering", "Thành thạo Python và SQL", "Có kinh nghiệm với big data tools"],
    benefits: ["Lương hấp dẫn", "Làm việc với data quy mô lớn", "Học hỏi công nghệ mới"],
    companyInfo: {
      name: "DataVerse",
      logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=DV",
      coverImageUrl: "https://images.unsplash.com/photo-1518186285589-2f7649de83e0?w=800&h=400&fit=crop",
      description: "DataVerse cung cấp giải pháp data platform cho doanh nghiệp lớn.",
      website: "https://dataverse.vn",
      industry: "Data & Analytics",
      size: "50-100 nhân viên",
      founded: 2019,
    },
    locationInfo: {
      city: "Hà Nội",
      district: "Đống Đa",
      address: "Tầng 6, Viettel Tower, 285 Cách Mạng Tháng 8",
      coordinates: { lat: 21.0108, lng: 105.8286 },
    },
    contactInfo: {
      name: "Bùi Minh Đức",
      title: "Engineering Manager",
      email: "duc.bui@dataverse.vn",
      phone: "+84 904 567 890",
    },
  },
  {
    id: "10",
    title: "QA Automation Engineer",
    company: "QualityFirst",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=QF",
    location: "TP. Hồ Chí Minh",
    type: "Full-time",
    level: "Junior",
    salary: "$700 - $1,200",
    postedAt: "2026-01-31T03:00:00.000Z",
    description: "Xây dựng và maintain automation test framework. Đảm bảo chất lượng sản phẩm.",
    skills: ["Selenium", "Cypress", "JavaScript", "API Testing"],
    requirements: ["1-2 năm kinh nghiệm QA", "Biết lập trình cơ bản", "Tư duy logic tốt"],
    benefits: ["Đào tạo bài bản", "Lộ trình lên Senior", "Môi trường thân thiện"],
    companyInfo: {
      name: "QualityFirst",
      logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=QF",
      coverImageUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&h=400&fit=crop",
      description: "QualityFirst chuyên cung cấp dịch vụ QA cho các công ty phần mềm.",
      website: "https://qualityfirst.vn",
      industry: "QA Services",
      size: "30-50 nhân viên",
      founded: 2017,
    },
    locationInfo: {
      city: "TP. Hồ Chí Minh",
      district: "Tân Bình",
      address: "Tòa nhà E-Town, 364 Cộng Hòa",
      coordinates: { lat: 10.8012, lng: 106.6427 },
    },
    contactInfo: {
      name: "Trần Thị Hồng",
      title: "QA Manager",
      email: "hong.tran@qualityfirst.vn",
      phone: "+84 911 234 567",
    },
  },
  {
    id: "11",
    title: "iOS Developer",
    company: "MobileFirst",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=MF",
    location: "TP. Hồ Chí Minh",
    type: "Full-time",
    level: "Middle",
    salary: "$1,400 - $2,400",
    postedAt: "2026-01-30T21:00:00.000Z",
    description: "Phát triển ứng dụng iOS native với Swift. Tham gia vào các dự án fintech lớn.",
    skills: ["Swift", "SwiftUI", "UIKit", "Core Data", "Combine"],
    requirements: ["3+ năm kinh nghiệm iOS", "Thành thạo Swift", "Hiểu biết về App Store guidelines"],
    benefits: ["Lương tháng 13-14", "MacBook mới", "Bảo hiểm cao cấp"],
    companyInfo: {
      name: "MobileFirst",
      logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=MF",
      coverImageUrl: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=400&fit=crop",
      description: "MobileFirst là công ty chuyên phát triển ứng dụng native cho iOS và Android.",
      website: "https://mobilefirst.vn",
      industry: "Mobile Development",
      size: "40-60 nhân viên",
      founded: 2016,
    },
    locationInfo: {
      city: "TP. Hồ Chí Minh",
      district: "Bình Thạnh",
      address: "Tòa nhà Pearl Plaza, 561A Điện Biên Phủ",
      coordinates: { lat: 10.8019, lng: 106.7104 },
    },
    contactInfo: {
      name: "Nguyễn Hoàng Long",
      title: "iOS Team Lead",
      email: "long.nguyen@mobilefirst.vn",
      phone: "+84 913 456 789",
    },
  },
  {
    id: "12",
    title: "Android Developer",
    company: "MobileFirst",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=MF",
    location: "TP. Hồ Chí Minh",
    type: "Full-time",
    level: "Senior",
    salary: "$1,800 - $3,200",
    postedAt: "2026-01-30T19:00:00.000Z",
    description: "Phát triển ứng dụng Android native với Kotlin. Lead team 3-4 developers.",
    skills: ["Kotlin", "Jetpack Compose", "MVVM", "Coroutines", "Dagger/Hilt"],
    requirements: ["5+ năm kinh nghiệm Android", "Thành thạo Kotlin", "Có kinh nghiệm lead team nhỏ"],
    benefits: ["Lương tháng 13-14", "Thiết bị Android mới nhất", "Budget learning"],
    companyInfo: {
      name: "MobileFirst",
      logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=MF",
      coverImageUrl: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&h=400&fit=crop",
      description: "MobileFirst là công ty chuyên phát triển ứng dụng native cho iOS và Android.",
      website: "https://mobilefirst.vn",
      industry: "Mobile Development",
      size: "40-60 nhân viên",
      founded: 2016,
    },
    locationInfo: {
      city: "TP. Hồ Chí Minh",
      district: "Bình Thạnh",
      address: "Tòa nhà Pearl Plaza, 561A Điện Biên Phủ",
      coordinates: { lat: 10.8019, lng: 106.7104 },
    },
    contactInfo: {
      name: "Lê Văn Thắng",
      title: "Android Team Lead",
      email: "thang.le@mobilefirst.vn",
      phone: "+84 914 567 890",
    },
  },
  {
    id: "13",
    title: "Security Engineer",
    company: "CyberShield",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=CY",
    location: "Hà Nội",
    type: "Full-time",
    level: "Senior",
    salary: "$2,500 - $4,000",
    postedAt: "2026-01-27T10:00:00.000Z",
    description: "Bảo vệ hệ thống khỏi các mối đe dọa. Thực hiện penetration testing và security audit.",
    skills: ["Penetration Testing", "OWASP", "Network Security", "Python", "Linux"],
    requirements: ["5+ năm kinh nghiệm Security", "Có chứng chỉ CEH/OSCP", "Kinh nghiệm với cloud security"],
    benefits: ["Lương cao", "Làm việc với các hệ thống lớn", "Training chứng chỉ quốc tế"],
    companyInfo: {
      name: "CyberShield",
      logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=CY",
      coverImageUrl: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&h=400&fit=crop",
      description: "CyberShield là công ty an ninh mạng hàng đầu Việt Nam.",
      website: "https://cybershield.vn",
      industry: "Cybersecurity",
      size: "30-50 nhân viên",
      founded: 2018,
    },
    locationInfo: {
      city: "Hà Nội",
      district: "Hoàn Kiếm",
      address: "Tầng 18, Lotte Center, 54 Liễu Giai",
      coordinates: { lat: 21.0318, lng: 105.8122 },
    },
    contactInfo: {
      name: "Trần Quốc Bảo",
      title: "Security Director",
      email: "bao.tran@cybershield.vn",
      phone: "+84 902 345 678",
    },
  },
  {
    id: "14",
    title: "Product Manager",
    company: "ProductLab",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=PL",
    location: "TP. Hồ Chí Minh",
    type: "Full-time",
    level: "Senior",
    salary: "$2,000 - $3,500",
    postedAt: "2026-01-29T10:00:00.000Z",
    description: "Định hình roadmap sản phẩm và làm việc với các team cross-functional.",
    skills: ["Product Strategy", "Agile", "User Research", "Data Analysis", "Jira"],
    requirements: ["4+ năm kinh nghiệm PM", "Có background kỹ thuật", "Kỹ năng communication xuất sắc"],
    benefits: ["Lương cạnh tranh", "Stock options", "Flexible working"],
    companyInfo: {
      name: "ProductLab",
      logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=PL",
      coverImageUrl: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=400&fit=crop",
      description: "ProductLab xây dựng sản phẩm công nghệ cho thị trường Đông Nam Á.",
      website: "https://productlab.io",
      industry: "Product Development",
      size: "60-100 nhân viên",
      founded: 2019,
    },
    locationInfo: {
      city: "TP. Hồ Chí Minh",
      district: "Quận 1",
      address: "Tầng 20, Vietcombank Tower, 5 Công Trường Mê Linh",
      coordinates: { lat: 10.7763, lng: 106.7046 },
    },
    contactInfo: {
      name: "Đinh Thị Hương",
      title: "Head of People",
      email: "huong.dinh@productlab.io",
      phone: "+84 915 678 901",
    },
  },
  {
    id: "15",
    title: "Technical Writer",
    company: "DocuTech",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=DT",
    location: "Remote",
    type: "Part-time",
    level: "Middle",
    salary: "$800 - $1,500",
    postedAt: "2026-01-25T10:00:00.000Z",
    description: "Viết tài liệu kỹ thuật, API documentation và user guides cho các sản phẩm công nghệ.",
    skills: ["Technical Writing", "API Documentation", "Markdown", "Git"],
    requirements: ["2+ năm kinh nghiệm technical writing", "Tiếng Anh xuất sắc", "Hiểu biết về phát triển phần mềm"],
    benefits: ["Làm việc part-time linh hoạt", "Remote hoàn toàn", "Trả lương theo bài"],
    companyInfo: {
      name: "DocuTech",
      logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=DT",
      coverImageUrl: "https://images.unsplash.com/photo-1456324504439-367cee3b3c32?w=800&h=400&fit=crop",
      description: "DocuTech cung cấp dịch vụ documentation cho các công ty tech.",
      website: "https://docutech.io",
      industry: "Technical Documentation",
      size: "10-20 nhân viên",
      founded: 2020,
    },
    locationInfo: { city: "Remote", address: "Làm việc từ xa" },
    contactInfo: {
      name: "Nguyễn Thanh Tùng",
      title: "Content Manager",
      email: "tung.nguyen@docutech.io",
      phone: "+84 916 789 012",
    },
  },
  {
    id: "16",
    title: "Blockchain Developer",
    company: "Web3Labs",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=W3",
    location: "Remote",
    type: "Remote",
    level: "Senior",
    salary: "$4,000 - $7,000",
    postedAt: "2026-01-31T05:00:00.000Z",
    description: "Phát triển smart contracts và DApps trên các nền tảng blockchain.",
    skills: ["Solidity", "Ethereum", "Web3.js", "DeFi", "Smart Contracts"],
    requirements: ["3+ năm kinh nghiệm blockchain", "Thành thạo Solidity", "Hiểu biết sâu về DeFi protocols"],
    benefits: ["Lương USD cao", "Token allocation", "Remote worldwide"],
    companyInfo: {
      name: "Web3Labs",
      logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=W3",
      coverImageUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&h=400&fit=crop",
      description: "Web3Labs xây dựng các sản phẩm DeFi và NFT cho thị trường toàn cầu.",
      website: "https://web3labs.io",
      industry: "Blockchain / Web3",
      size: "20-40 nhân viên",
      founded: 2021,
    },
    locationInfo: { city: "Remote", address: "Làm việc từ xa - Toàn cầu" },
    contactInfo: {
      name: "Alex Tran",
      title: "Co-founder",
      email: "alex@web3labs.io",
      phone: "+84 917 890 123",
    },
  },
  {
    id: "17",
    title: "SRE Engineer",
    company: "Uptime99",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=U9",
    location: "TP. Hồ Chí Minh",
    type: "Full-time",
    level: "Senior",
    salary: "$2,500 - $4,500",
    postedAt: "2026-01-30T03:00:00.000Z",
    description: "Đảm bảo độ tin cậy và hiệu suất của hệ thống. On-call rotation và incident management.",
    skills: ["Linux", "Prometheus", "Grafana", "Python", "Incident Management"],
    requirements: ["5+ năm kinh nghiệm Ops/SRE", "Kinh nghiệm với high-traffic systems", "On-call experience"],
    benefits: ["Lương cao + on-call allowance", "Remote khi không on-call", "Training liên tục"],
    companyInfo: {
      name: "Uptime99",
      logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=U9",
      coverImageUrl: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&h=400&fit=crop",
      description: "Uptime99 cung cấp dịch vụ SRE-as-a-Service cho các công ty lớn.",
      website: "https://uptime99.io",
      industry: "SRE Services",
      size: "30-50 nhân viên",
      founded: 2019,
    },
    locationInfo: {
      city: "TP. Hồ Chí Minh",
      district: "Quận 2",
      address: "Tòa nhà Sonatus, 15 Lê Thánh Tôn, Thủ Đức",
      coordinates: { lat: 10.7886, lng: 106.7512 },
    },
    contactInfo: {
      name: "Phạm Anh Quân",
      title: "VP of Engineering",
      email: "quan.pham@uptime99.io",
      phone: "+84 918 901 234",
    },
  },
  {
    id: "18",
    title: "Machine Learning Engineer",
    company: "AIFactory",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=AF",
    location: "Hà Nội",
    type: "Full-time",
    level: "Middle",
    salary: "$1,800 - $3,000",
    postedAt: "2026-01-29T07:00:00.000Z",
    description: "Xây dựng và deploy các mô hình ML vào production. Làm việc với computer vision và NLP.",
    skills: ["Python", "TensorFlow", "PyTorch", "MLOps", "Computer Vision"],
    requirements: ["3+ năm kinh nghiệm ML", "Có kinh nghiệm deploy model lên production", "Background về toán và thống kê"],
    benefits: ["GPU workstation", "Ngân sách research", "Conference budget"],
    companyInfo: {
      name: "AIFactory",
      logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=AF",
      coverImageUrl: "https://images.unsplash.com/photo-1555255707-c07966088b7b?w=800&h=400&fit=crop",
      description: "AIFactory phát triển các giải pháp AI cho doanh nghiệp.",
      website: "https://aifactory.vn",
      industry: "Artificial Intelligence",
      size: "40-60 nhân viên",
      founded: 2018,
    },
    locationInfo: {
      city: "Hà Nội",
      district: "Nam Từ Liêm",
      address: "Tầng 5, FPT Tower, 10 Phạm Văn Bạch",
      coordinates: { lat: 21.0388, lng: 105.7814 },
    },
    contactInfo: {
      name: "Vũ Thị Ngọc",
      title: "AI Team Lead",
      email: "ngoc.vu@aifactory.vn",
      phone: "+84 919 012 345",
    },
  },
  {
    id: "19",
    title: "Scrum Master",
    company: "AgileWorks",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=AW",
    location: "TP. Hồ Chí Minh",
    type: "Full-time",
    level: "Senior",
    salary: "$1,500 - $2,500",
    postedAt: "2026-01-23T10:00:00.000Z",
    description: "Facilitate Scrum ceremonies và coach team về Agile practices.",
    skills: ["Scrum", "Agile", "Jira", "Confluence", "Team Coaching"],
    requirements: ["3+ năm kinh nghiệm Scrum Master", "Chứng chỉ CSM/PSM", "Kỹ năng facilitation tốt"],
    benefits: ["Làm việc với multiple teams", "Training Agile nâng cao", "Work-life balance"],
    companyInfo: {
      name: "AgileWorks",
      logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=AW",
      coverImageUrl: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&h=400&fit=crop",
      description: "AgileWorks cung cấp dịch vụ tư vấn và coaching Agile cho doanh nghiệp.",
      website: "https://agileworks.vn",
      industry: "Agile Consulting",
      size: "20-30 nhân viên",
      founded: 2017,
    },
    locationInfo: {
      city: "TP. Hồ Chí Minh",
      district: "Phú Nhuận",
      address: "Tòa nhà AB Tower, 76A Lê Lai",
      coordinates: { lat: 10.7941, lng: 106.6802 },
    },
    contactInfo: {
      name: "Nguyễn Minh Châu",
      title: "Agile Coach",
      email: "chau.nguyen@agileworks.vn",
      phone: "+84 910 123 456",
    },
  },
  {
    id: "20",
    title: "UX Researcher",
    company: "InsightUX",
    logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=IX",
    location: "Đà Nẵng",
    type: "Full-time",
    level: "Middle",
    salary: "$1,200 - $2,000",
    postedAt: "2026-01-28T10:00:00.000Z",
    description: "Thực hiện user research và usability testing để cải thiện trải nghiệm sản phẩm.",
    skills: ["User Research", "Usability Testing", "User Interviews", "Data Analysis", "Figma"],
    requirements: ["2+ năm kinh nghiệm UX Research", "Kỹ năng phân tích tốt", "Communication skills xuất sắc"],
    benefits: ["Làm việc với nhiều loại sản phẩm", "Research budget", "Văn phòng view biển"],
    companyInfo: {
      name: "InsightUX",
      logoUrl: "https://api.dicebear.com/7.x/initials/svg?seed=IX",
      coverImageUrl: "https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=800&h=400&fit=crop",
      description: "InsightUX là UX agency tập trung vào research-driven design.",
      website: "https://insightux.vn",
      industry: "UX Research",
      size: "15-25 nhân viên",
      founded: 2020,
    },
    locationInfo: {
      city: "Đà Nẵng",
      district: "Sơn Trà",
      address: "Tòa nhà Danang Software Park, Quang Trung",
      coordinates: { lat: 16.0678, lng: 108.2208 },
    },
    contactInfo: {
      name: "Lê Thị Kim Ngân",
      title: "Research Lead",
      email: "ngan.le@insightux.vn",
      phone: "+84 920 234 567",
    },
  },
];

// Helper function to get job by ID
export function getJobById(id: string): Job | undefined {
  return mockJobs.find((job) => job.id === id);
}
